"""
DPDPA Compliance Document Generator
Generates rule-based DPDPA compliance documents as DOCX files.
Part of the Anumati.ai tool.
"""

import os
from datetime import datetime
from typing import List, Dict, Optional
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


class DocumentGenerator:
    """Generate DPDPA-compliant documents in DOCX format."""

    def __init__(self, output_dir: str = "/tmp/anumati_docs/"):
        """
        Initialize the document generator.

        Args:
            output_dir: Directory to save generated documents.
        """
        self.output_dir = output_dir
        self.generation_date = datetime.now().strftime("%d-%m-%Y")

        # Create output directory if it doesn't exist
        os.makedirs(output_dir, exist_ok=True)

    def _create_document(self, title: str, org_name: str) -> Document:
        """
        Create a new document with standard formatting.

        Args:
            title: Document title
            org_name: Organization name

        Returns:
            Document object with header, title, and footer
        """
        doc = Document()

        # Set up header with organization name
        section = doc.sections[0]
        header = section.header
        header_para = header.paragraphs[0]
        header_para.text = org_name
        header_para.style = 'Header'

        # Set up footer with generation info
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by Anumati.ai | {self.generation_date}"
        footer_para.style = 'Footer'
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add title
        title_para = doc.add_paragraph()
        title_run = title_para.add_run(title)
        title_run.font.size = Pt(18)
        title_run.font.bold = True
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add generation date
        date_para = doc.add_paragraph()
        date_run = date_para.add_run(f"Generated on: {self.generation_date}")
        date_run.font.size = Pt(10)
        date_run.font.italic = True
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()  # Spacing
        return doc

    def _add_section(self, doc: Document, heading: str, content: str = None) -> None:
        """
        Add a section with heading and optional content.

        Args:
            doc: Document object
            heading: Section heading
            content: Optional section content
        """
        heading_para = doc.add_paragraph(heading, style='Heading 1')
        heading_para.paragraph_format.space_before = Pt(12)
        heading_para.paragraph_format.space_after = Pt(6)

        if content:
            content_para = doc.add_paragraph(content)
            content_para.paragraph_format.space_after = Pt(6)

    def _add_subsection(self, doc: Document, heading: str, content: str = None) -> None:
        """
        Add a subsection with heading and optional content.

        Args:
            doc: Document object
            heading: Subsection heading
            content: Optional section content
        """
        heading_para = doc.add_paragraph(heading, style='Heading 2')
        heading_para.paragraph_format.space_before = Pt(8)
        heading_para.paragraph_format.space_after = Pt(4)

        if content:
            content_para = doc.add_paragraph(content)
            content_para.paragraph_format.space_after = Pt(4)

    def _save_document(self, doc: Document, filename: str) -> str:
        """
        Save document to file.

        Args:
            doc: Document object
            filename: Name of the file

        Returns:
            Full file path
        """
        filepath = os.path.join(self.output_dir, filename)
        doc.save(filepath)
        return filepath

    def generate_privacy_policy(
        self,
        org_name: str,
        industry: str,
        data_categories: List[str],
        purposes: List[str],
        retention_period: str,
        contact_email: str,
        dpo_name: str,
    ) -> str:
        """
        Generate a DPDPA-compliant Privacy Policy.

        Args:
            org_name: Organization name
            industry: Industry/sector
            data_categories: List of data categories collected
            purposes: List of processing purposes
            retention_period: Data retention period
            contact_email: Contact email for inquiries
            dpo_name: Data Protection Officer name

        Returns:
            Path to generated document
        """
        doc = self._create_document("Privacy Policy", org_name)

        # Introduction
        self._add_section(
            doc,
            "1. Introduction",
            f"{org_name} (hereinafter 'Data Controller' or 'We') respects your privacy and is "
            "committed to protecting your personal data. This Privacy Policy explains how we collect, "
            "process, and protect your data in compliance with the Digital Personal Data Protection "
            "Act, 2023 (DPDPA)."
        )

        # Definitions
        self._add_section(doc, "2. Definitions")
        defs = [
            "Personal Data: Any information relating to an identifiable natural person.",
            "Processing: Any operation performed on personal data such as collection, recording, "
            "storage, adaptation, retrieval, consultation, use, transmission, or erasure.",
            "Data Principal: The natural person to whom personal data relates.",
            "Data Controller: The entity that determines the purposes and means of processing personal data.",
            "Data Processor: An entity that processes personal data on behalf of the Data Controller.",
            "Cross-Border Transfer: Transfer of personal data outside India.",
        ]
        for definition in defs:
            doc.add_paragraph(definition, style='List Bullet')

        # Data We Collect
        self._add_section(doc, "3. Data We Collect")
        self._add_subsection(doc, "3.1 Categories of Data")
        doc.add_paragraph(
            "We collect the following categories of personal data from Data Principals:"
        )
        for category in data_categories:
            doc.add_paragraph(f"[{category}]", style='List Bullet')

        self._add_subsection(
            doc,
            "3.2 Sources of Data",
            "We collect data directly from you through: online forms, website interactions, "
            "customer service interactions, purchases, registrations, and communications."
        )

        # Purpose of Processing
        self._add_section(doc, "4. Purpose of Processing (Section 4, DPDPA)")
        doc.add_paragraph(
            "We process your personal data for the following purposes, each with separate consent:"
        )
        for idx, purpose in enumerate(purposes, 1):
            doc.add_paragraph(f"[Purpose {idx}: {purpose}]", style='List Bullet')

        # Legal Basis
        self._add_section(doc, "5. Legal Basis for Processing (Section 6, DPDPA)")
        self._add_subsection(doc, "5.1 Consent")
        doc.add_paragraph(
            "Processing for non-sensitive personal data is based on your consent obtained through "
            "our Consent Notice. You have the right to withdraw consent at any time."
        )

        self._add_subsection(doc, "5.2 Legitimate Interests")
        doc.add_paragraph(
            "[Where applicable: We process data based on our legitimate interests and your rights "
            "are not overridden.]"
        )

        self._add_subsection(doc, "5.3 Legal Obligation")
        doc.add_paragraph(
            "[Where applicable: Processing is necessary to comply with legal obligations "
            "under law.]"
        )

        # Data Principal Rights
        self._add_section(doc, "6. Your Rights as a Data Principal (Sections 8-12, DPDPA)")

        self._add_subsection(
            doc,
            "6.1 Right to Access (Section 8)",
            "You have the right to access your personal data held by us. Submit a written request "
            "to [CONTACT_EMAIL]. We will provide the data within 30 days in structured, common, "
            "machine-readable format."
        )

        self._add_subsection(
            doc,
            "6.2 Right to Correction (Section 9)",
            "You may correct inaccurate, incomplete, or outdated personal data. Submit corrections "
            "to [CONTACT_EMAIL]. We will make corrections within 30 days."
        )

        self._add_subsection(
            doc,
            "6.3 Right to Erasure (Section 10)",
            "You can request erasure of your data in cases where: (a) it is no longer necessary for "
            "the purpose collected, (b) you withdraw consent, or (c) processing is unlawful. We will "
            "delete data within 30 days unless legally obligated to retain it."
        )

        self._add_subsection(
            doc,
            "6.4 Right to Grievance Redressal (Section 13)",
            "You have the right to file a grievance for any violation of DPDPA. Contact our DPO "
            "or file a complaint with the Data Protection Board."
        )

        self._add_subsection(
            doc,
            "6.5 Right to Nominate (Section 12)",
            "You may nominate a person to exercise your rights post-death."
        )

        # Data Retention
        self._add_section(
            doc,
            "7. Data Retention",
            f"We retain your personal data for [RETENTION_PERIOD: {retention_period}]. After this period, "
            "data is securely deleted unless legally required to be retained. You may request earlier "
            "deletion if the purpose is fulfilled."
        )

        # Security Measures
        self._add_section(doc, "8. Security Measures (Section 7, DPDPA)")
        security_measures = [
            "Encryption of data in transit and at rest using industry-standard encryption",
            "Regular security audits and penetration testing",
            "Access controls and authentication mechanisms",
            "Employee training on data protection and privacy practices",
            "Incident response procedures for data breaches",
            "Physical security measures for data centers",
        ]
        for measure in security_measures:
            doc.add_paragraph(measure, style='List Bullet')

        # Cross-Border Transfers
        self._add_section(doc, "9. Cross-Border Data Transfers (Section 17, DPDPA)")
        doc.add_paragraph(
            "[Where applicable: We may transfer personal data outside India only when: "
            "(a) you have given explicit consent, (b) it is necessary for contract performance, "
            "(c) it is required by law, or (d) the country has an adequate level of data protection.] "
            "We implement Standard Contractual Clauses (SCCs) or other safeguards as required."
        )

        # Children's Data
        self._add_section(doc, "10. Processing of Children's Data (Section 16, DPDPA)")
        doc.add_paragraph(
            "We do not knowingly collect personal data from children under 18 years. For any data "
            "from minors, we obtain consent from their parents/guardians. If we become aware that "
            "we have collected data from a child without parental consent, we will delete it immediately."
        )

        # Grievance Redressal
        self._add_section(doc, "11. Grievance Redressal Mechanism (Section 13, DPDPA)")
        doc.add_paragraph(
            f"Data Protection Officer: {dpo_name}\nEmail: {contact_email}\n\n"
            "We acknowledge grievances within 48 hours and resolve them within 90 days. "
            "If not satisfied, you may approach the Data Protection Board."
        )

        # Changes to Policy
        self._add_section(
            doc,
            "12. Changes to This Policy",
            "We may update this Privacy Policy periodically. Major changes will be communicated "
            "to you via email or prominent notice on our website. Continued use implies acceptance."
        )

        # Contact Information
        self._add_section(doc, "13. Contact Information")
        contact_info = [
            f"Organization: {org_name}",
            f"Industry: {industry}",
            f"Email: {contact_email}",
            f"Data Protection Officer: {dpo_name}",
        ]
        for info in contact_info:
            doc.add_paragraph(info)

        # DPDPA Compliance Reference
        doc.add_paragraph()
        compliance_ref = doc.add_paragraph(
            "This Privacy Policy is compliant with the Digital Personal Data Protection Act, 2023 "
            "and associated Rules."
        )
        compliance_ref.paragraph_format.space_before = Pt(12)

        return self._save_document(doc, "Privacy_Policy.docx")

    def generate_consent_notice(
        self,
        org_name: str,
        purpose: str,
        data_categories: List[str],
        processors: List[str],
        retention: str,
    ) -> str:
        """
        Generate an itemized Consent Notice per Section 5 / Rule 3, DPDPA.

        Args:
            org_name: Organization name
            purpose: Purpose of processing
            data_categories: Categories of data to be processed
            processors: List of processors who will handle data
            retention: Data retention period

        Returns:
            Path to generated document
        """
        doc = self._create_document("Consent Notice", org_name)

        # Introduction
        self._add_section(
            doc,
            "Consent Notice - Section 5, Rule 3, DPDPA",
            f"{org_name} requests your explicit, informed, and voluntary consent to process "
            "your personal data as detailed below."
        )

        # Consent Requirements
        self._add_section(doc, "1. Consent Requirements")
        requirements = [
            "Free: You are under no obligation to provide consent.",
            "Specific: Consent is requested separately for each purpose.",
            "Informed: You are fully informed about data processing practices.",
            "Unconditional: Your consent is not conditional on accepting irrelevant conditions.",
            "Unambiguous: We make clear what we are asking your consent for.",
        ]
        for req in requirements:
            doc.add_paragraph(req, style='List Bullet')

        # Data Categories
        self._add_section(doc, "2. Categories of Personal Data We Collect")
        for category in data_categories:
            doc.add_paragraph(f"[{category}]", style='List Bullet')

        # Purpose of Processing
        self._add_section(doc, "3. Purpose of Processing")
        doc.add_paragraph(f"[Purpose: {purpose}]")
        doc.add_paragraph(
            "Processing is limited to this specified purpose. If we wish to use your data "
            "for a different purpose, we will seek separate consent."
        )

        # Data Processors
        self._add_section(doc, "4. Data Processors")
        doc.add_paragraph(
            "The following entities may process your data on our behalf under strict "
            "data processing agreements:"
        )
        for processor in processors:
            doc.add_paragraph(f"[{processor}]", style='List Bullet')

        # Data Retention
        self._add_section(doc, "5. Data Retention Period")
        doc.add_paragraph(
            f"Your personal data will be retained for: [{retention}]\n"
            "After this period, your data will be securely deleted unless we are legally "
            "required to retain it."
        )

        # Your Rights
        self._add_section(doc, "6. Your Rights")
        rights = [
            "Right to Access: Request a copy of your personal data.",
            "Right to Correction: Correct inaccurate or incomplete data.",
            "Right to Erasure: Request deletion of your data under certain conditions.",
            "Right to Withdraw Consent: Withdraw your consent at any time by contacting us.",
            "Right to Grievance: File a grievance with our DPO or the Data Protection Board.",
        ]
        for right in rights:
            doc.add_paragraph(right, style='List Bullet')

        # Withdrawal of Consent
        self._add_section(doc, "7. How to Withdraw Consent")
        doc.add_paragraph(
            "You can withdraw your consent at any time by:\n"
            "- Sending an email to [CONTACT_EMAIL]\n"
            "- Submitting a written request to [OFFICE_ADDRESS]\n"
            "- Using the 'Unsubscribe' link in communications from us\n\n"
            "Withdrawal will not affect the validity of processing done before withdrawal."
        )

        # Consent Statement
        self._add_section(doc, "8. Consent Statement")
        doc.add_paragraph(
            "By providing your signature below or clicking 'I Agree' digitally, you confirm that:"
        )
        confirmations = [
            "You have read and understood this Consent Notice.",
            "You have received clear information about our data processing practices.",
            "You freely and voluntarily provide consent to the processing described above.",
            "You understand you can withdraw consent at any time without penalty.",
        ]
        for confirmation in confirmations:
            doc.add_paragraph(confirmation, style='List Bullet')

        # Sign-off Section
        doc.add_paragraph()
        sign_off = doc.add_paragraph("Signature/Consent: ________________     Date: ________________")
        sign_off.paragraph_format.space_before = Pt(12)

        return self._save_document(doc, "Consent_Notice.docx")

    def generate_dpa(
        self,
        controller_name: str,
        processor_name: str,
        processing_purposes: List[str],
        data_types: List[str],
    ) -> str:
        """
        Generate a Data Processing Agreement (DPA) template.

        Args:
            controller_name: Name of the Data Controller
            processor_name: Name of the Data Processor
            processing_purposes: List of processing purposes
            data_types: Types of data to be processed

        Returns:
            Path to generated document
        """
        doc = self._create_document("Data Processing Agreement", controller_name)

        # Preamble
        self._add_section(doc, "1. Definitions")
        defs = [
            f"Data Controller: {controller_name}",
            f"Data Processor: {processor_name}",
            "Personal Data: Any information relating to an identifiable natural person.",
            "Processing: Any operation performed on personal data.",
            "Data Principal: The natural person to whom personal data relates.",
        ]
        for definition in defs:
            doc.add_paragraph(definition, style='List Bullet')

        # Scope
        self._add_section(doc, "2. Scope and Objectives")
        self._add_subsection(
            doc,
            "2.1 Purpose",
            "This Agreement defines the terms under which the Processor shall process personal data "
            "on behalf of the Controller in compliance with DPDPA."
        )

        self._add_subsection(doc, "2.2 Processing Purposes")
        for purpose in processing_purposes:
            doc.add_paragraph(f"[{purpose}]", style='List Bullet')

        self._add_subsection(doc, "2.3 Data Types")
        for data_type in data_types:
            doc.add_paragraph(f"[{data_type}]", style='List Bullet')

        # Processing Instructions
        self._add_section(doc, "3. Processing Instructions (Section 6, DPDPA)")
        self._add_subsection(
            doc,
            "3.1 Authority",
            "The Processor shall process personal data only on documented instructions "
            "from the Controller."
        )
        self._add_subsection(
            doc,
            "3.2 Personnel Confidentiality",
            "The Processor shall ensure that any person authorized to process personal data "
            "commits to confidentiality."
        )
        self._add_subsection(
            doc,
            "3.3 Limitations",
            "The Processor shall not process data for purposes other than those specified "
            "in this Agreement without prior written consent from the Controller."
        )

        # Security Measures
        self._add_section(doc, "4. Security Measures (Section 7, DPDPA)")
        measures = [
            "Encryption of data in transit and at rest",
            "Access control and authentication mechanisms",
            "Regular security audits and assessments",
            "Secure deletion and destruction procedures",
            "Business continuity and disaster recovery plans",
            "Regular staff training on data protection",
        ]
        for measure in measures:
            doc.add_paragraph(measure, style='List Bullet')

        # Sub-processors
        self._add_section(doc, "5. Sub-processors")
        doc.add_paragraph(
            "The Processor shall not engage sub-processors without prior written authorization "
            "from the Controller. The Processor remains liable to the Controller for the "
            "performance of sub-processors."
        )

        # Audit Rights
        self._add_section(doc, "6. Audit Rights")
        doc.add_paragraph(
            "The Controller has the right to audit the Processor's compliance with this "
            "Agreement. The Processor shall provide assistance and access to relevant records, "
            "systems, and personnel for such audits."
        )

        # Data Breach Notification
        self._add_section(doc, "7. Data Breach Notification (Section 7(3), DPDPA)")
        doc.add_paragraph(
            "The Processor shall notify the Controller without undue delay (within 24 hours) "
            "upon becoming aware of any personal data breach. The notification shall include: "
            "nature of the breach, data affected, number of individuals, likely consequences, "
            "and measures taken to address the breach."
        )

        # Data Principal Rights
        self._add_section(doc, "8. Data Principal Rights (Sections 8-12, DPDPA)")
        doc.add_paragraph(
            "The Processor shall assist the Controller in responding to Data Principal requests "
            "for access, correction, erasure, and grievance redressal within stipulated timelines."
        )

        # Return or Deletion of Data
        self._add_section(doc, "9. Return or Deletion of Data")
        doc.add_paragraph(
            "Upon termination of this Agreement, the Processor shall, at the Controller's choice: "
            "(a) return all personal data in a structured, machine-readable format, or "
            "(b) securely delete all personal data and provide written confirmation of deletion."
        )

        # Liability
        self._add_section(doc, "10. Liability and Indemnification")
        doc.add_paragraph(
            "The Processor shall indemnify the Controller against any claims, damages, or costs "
            "arising from the Processor's violation of this Agreement or applicable data protection laws."
        )

        # Term and Termination
        self._add_section(doc, "11. Term and Termination")
        self._add_subsection(doc, "11.1 Effective Date")
        doc.add_paragraph("[Insert effective date]")

        self._add_subsection(doc, "11.2 Duration")
        doc.add_paragraph("[Insert duration or 'Until terminated by either party']")

        self._add_subsection(doc, "11.3 Termination Rights")
        doc.add_paragraph(
            "Either party may terminate this Agreement with [30 DAYS] written notice. "
            "Upon termination, the Processor shall cease processing immediately."
        )

        # Signatures
        doc.add_paragraph()
        sig_section = doc.add_paragraph("Signatures:")
        sig_section.paragraph_format.space_before = Pt(12)

        sig_table = doc.add_table(rows=3, cols=2)
        sig_table.autofit = False
        sig_table.allow_autofit = False

        sig_cells = sig_table.rows[0].cells
        sig_cells[0].text = "Data Controller"
        sig_cells[1].text = f"Name: {controller_name}"

        sig_cells = sig_table.rows[1].cells
        sig_cells[0].text = "Signature: ____________________"
        sig_cells[1].text = f"Date: ____________________"

        sig_cells = sig_table.rows[2].cells
        sig_cells[0].text = "Data Processor"
        sig_cells[1].text = f"Name: {processor_name}"

        return self._save_document(doc, "Data_Processing_Agreement.docx")

    def generate_dpia(
        self,
        org_name: str,
        project_name: str,
        processing_description: str,
        data_types: List[str],
        risk_assessment: Dict[str, str],
    ) -> str:
        """
        Generate a Data Protection Impact Assessment (DPIA) Report.

        Args:
            org_name: Organization name
            project_name: Name of the project/processing activity
            processing_description: Description of the processing
            data_types: Types of data involved
            risk_assessment: Dictionary with risk factors and mitigation

        Returns:
            Path to generated document
        """
        doc = self._create_document("Data Protection Impact Assessment Report", org_name)

        # Executive Summary
        self._add_section(
            doc,
            "1. Executive Summary",
            f"This DPIA assesses the data protection risks associated with [{project_name}] "
            "processing activity and recommends mitigation measures to ensure compliance with DPDPA."
        )

        # Project Overview
        self._add_section(doc, "2. Project Overview")
        self._add_subsection(doc, "2.1 Project Name")
        doc.add_paragraph(f"[{project_name}]")

        self._add_subsection(doc, "2.2 Organization")
        doc.add_paragraph(f"[{org_name}]")

        self._add_subsection(doc, "2.3 Processing Description")
        doc.add_paragraph(f"[{processing_description}]")

        self._add_subsection(doc, "2.4 Data Types Involved")
        for data_type in data_types:
            doc.add_paragraph(f"[{data_type}]", style='List Bullet')

        # Legal Basis
        self._add_section(doc, "3. Legal Basis for Processing")
        doc.add_paragraph(
            "Consent, Legitimate Interest, Legal Obligation, or other valid basis per DPDPA Section 6"
        )

        # Risk Assessment Matrix
        self._add_section(doc, "4. Risk Assessment Matrix")
        doc.add_paragraph(
            "Risk Level = Likelihood × Impact\n"
            "Low: 1-2 | Medium: 3-6 | High: 8-9 | Critical: 10-12"
        )

        # Create risk table
        risk_table = doc.add_table(rows=5, cols=4)
        risk_table.style = 'Light Grid Accent 1'

        hdr_cells = risk_table.rows[0].cells
        hdr_cells[0].text = "Risk Factor"
        hdr_cells[1].text = "Likelihood"
        hdr_cells[2].text = "Impact"
        hdr_cells[3].text = "Level"

        row_idx = 1
        for risk_name, mitigation in risk_assessment.items():
            cells = risk_table.rows[row_idx].cells
            cells[0].text = f"[{risk_name}]"
            cells[1].text = "[1-3]"
            cells[2].text = "[1-3]"
            cells[3].text = "[LOW/MEDIUM/HIGH]"
            row_idx += 1

        # Mitigation Measures
        self._add_section(doc, "5. Mitigation Measures")
        doc.add_paragraph(
            "The following measures shall be implemented to mitigate identified risks:"
        )
        for risk_name, mitigation in risk_assessment.items():
            self._add_subsection(doc, f"5.{list(risk_assessment.keys()).index(risk_name) + 1} {risk_name}")
            doc.add_paragraph(f"[Mitigation: {mitigation}]")

        # Residual Risk Assessment
        self._add_section(doc, "6. Residual Risk Assessment")
        doc.add_paragraph(
            "After implementation of mitigation measures:\n"
            "[Assess whether residual risks are acceptable and consistent with DPDPA compliance]"
        )

        # Recommendations
        self._add_section(doc, "7. Recommendations")
        recommendations = [
            "Implement encryption for data in transit and at rest",
            "Establish regular security audits and penetration testing",
            "Provide data protection training to all personnel",
            "Implement access controls and authentication mechanisms",
            "Establish incident response procedures for data breaches",
            "Monitor and review processing activities regularly",
        ]
        for rec in recommendations:
            doc.add_paragraph(f"[{rec}]", style='List Bullet')

        # Approval and Sign-off
        self._add_section(doc, "8. Sign-off")
        doc.add_paragraph(
            "Data Protection Officer: ________________ Date: ________________\n"
            "Project Lead: ________________ Date: ________________\n"
            "Organization Head: ________________ Date: ________________"
        )

        return self._save_document(doc, "DPIA_Report.docx")

    def generate_breach_notification(
        self,
        org_name: str,
        breach_date: str,
        discovery_date: str,
        description: str,
        data_affected: List[str],
        individuals_count: int,
        measures_taken: List[str],
    ) -> str:
        """
        Generate a Data Breach Notification document.

        Args:
            org_name: Organization name
            breach_date: Date when breach occurred
            discovery_date: Date when breach was discovered
            description: Description of the breach
            data_affected: Categories of data affected
            individuals_count: Number of Data Principals affected
            measures_taken: List of remedial measures taken

        Returns:
            Path to generated document
        """
        doc = self._create_document("Data Breach Notification", org_name)

        # Part 1: Notification to Data Protection Board
        self._add_section(doc, "PART 1: NOTIFICATION TO DATA PROTECTION BOARD")

        self._add_section(
            doc,
            "1. Notification Details (Section 7(3), DPDPA - Within 72 hours)"
        )

        notification_details = [
            f"Organization: {org_name}",
            f"Breach Date: {breach_date}",
            f"Discovery Date: {discovery_date}",
            f"Reporting Date: {self.generation_date}",
        ]
        for detail in notification_details:
            doc.add_paragraph(detail, style='List Bullet')

        self._add_section(doc, "2. Breach Description")
        doc.add_paragraph(f"[{description}]")

        self._add_section(doc, "3. Data Affected")
        for data_cat in data_affected:
            doc.add_paragraph(f"[{data_cat}]", style='List Bullet')

        self._add_section(
            doc,
            "4. Number of Data Principals Affected",
            f"Approximately [{individuals_count}] Data Principals have been affected."
        )

        self._add_section(doc, "5. Nature and Consequences of the Breach")
        doc.add_paragraph(
            "The breach has resulted in:\n"
            "- Unauthorized access to personal data\n"
            "- [Risk of identity theft/Financial loss/Other consequences]\n"
            "- [Impact assessment details]"
        )

        self._add_section(doc, "6. Measures Taken to Address the Breach")
        for measure in measures_taken:
            doc.add_paragraph(f"[{measure}]", style='List Bullet')

        self._add_section(doc, "7. Measures to Mitigate Harm")
        doc.add_paragraph(
            "- Notification to affected Data Principals\n"
            "- Offer of credit monitoring services\n"
            "- Enhanced security measures\n"
            "- [Additional preventive measures]"
        )

        # Part 2: Notification to Data Principals
        doc.add_page_break()
        self._add_section(doc, "PART 2: NOTIFICATION TO DATA PRINCIPALS")

        self._add_section(
            doc,
            "1. Notice to Affected Individuals",
            f"To the residents of India affected by the data breach at {org_name}:"
        )

        self._add_section(doc, "2. What Happened")
        doc.add_paragraph(
            f"On {breach_date}, we identified an unauthorized {description} affecting your "
            "personal information."
        )

        self._add_section(doc, "3. What Information Was Affected")
        for data_cat in data_affected:
            doc.add_paragraph(f"[{data_cat}]", style='List Bullet')

        self._add_section(doc, "4. What We Are Doing")
        doc.add_paragraph(
            "- Securing the breach and preventing further unauthorized access\n"
            "- Investigating the incident thoroughly\n"
            "- Implementing additional security measures\n"
            "- Notifying law enforcement authorities"
        )

        self._add_section(doc, "5. What You Can Do")
        actions = [
            "Review your personal information for suspicious activity",
            "Monitor your credit reports for unauthorized transactions",
            "Change passwords for online accounts",
            "Consider identity theft protection services",
            "Report any suspected fraud to relevant authorities",
        ]
        for action in actions:
            doc.add_paragraph(action, style='List Bullet')

        self._add_section(doc, "6. Contact Information for Questions")
        doc.add_paragraph(
            "If you have questions about this breach or our response, please contact:\n"
            "[Contact Name]\n"
            "[Contact Email]\n"
            "[Contact Phone]\n"
            "Data Protection Officer: [DPO Name]\n"
            "Email: [DPO Email]"
        )

        self._add_section(
            doc,
            "7. Regulatory Information",
            "This notification is provided in accordance with Section 7 of the Digital Personal "
            "Data Protection Act, 2023. For more information about data protection rights, "
            "contact the Data Protection Board."
        )

        return self._save_document(doc, "Breach_Notification.docx")

    def generate_ropa(
        self,
        org_name: str,
        processing_activities: List[Dict[str, str]],
    ) -> str:
        """
        Generate Records of Processing Activities (RoPA).

        Args:
            org_name: Organization name
            processing_activities: List of dicts with processing activity details

        Returns:
            Path to generated document
        """
        doc = self._create_document("Records of Processing Activities (RoPA)", org_name)

        # Introduction
        self._add_section(
            doc,
            "1. Introduction",
            f"This document contains the {org_name} Records of Processing Activities (RoPA) as "
            "required by DPDPA Section 19. It documents all personal data processing activities "
            "within the organization."
        )

        # Legal Requirement
        self._add_section(
            doc,
            "2. Legal Requirement (Section 19, DPDPA)",
            "Every entity that determines the purposes and means of personal data processing must "
            "maintain records of processing activities. This includes information on: purposes, "
            "categories of Data Principals, data categories, recipients, retention periods, "
            "and security measures."
        )

        # Processing Activities Table
        self._add_section(doc, "3. Processing Activities")

        # Create comprehensive table
        table = doc.add_table(rows=len(processing_activities) + 1, cols=9)
        table.style = 'Light Grid Accent 1'

        # Header row
        headers = [
            "Activity",
            "Purpose",
            "Legal Basis",
            "Data Categories",
            "Data Principals",
            "Recipients",
            "Retention",
            "Security Measures",
            "Cross-border",
        ]
        hdr_cells = table.rows[0].cells
        for idx, header in enumerate(headers):
            hdr_cells[idx].text = header

        # Data rows
        for row_idx, activity in enumerate(processing_activities, 1):
            cells = table.rows[row_idx].cells
            cells[0].text = activity.get("activity", "[Activity Name]")
            cells[1].text = activity.get("purpose", "[Purpose]")
            cells[2].text = activity.get("legal_basis", "[Consent/Legal Obligation/Etc.]")
            cells[3].text = activity.get("data_categories", "[Categories]")
            cells[4].text = activity.get("data_principals", "[Who]")
            cells[5].text = activity.get("recipients", "[Internal/Processors/External]")
            cells[6].text = activity.get("retention", "[Period]")
            cells[7].text = activity.get("security_measures", "[Encryption/Access Control/Etc.]")
            cells[8].text = activity.get("cross_border", "[Yes/No]")

        # Data Subject Rights
        self._add_section(doc, "4. Data Principal Rights")
        doc.add_paragraph(
            "For each processing activity, Data Principals have the following rights:"
        )
        rights = [
            "Right to Access: Obtain a copy of processed data",
            "Right to Correction: Correct inaccurate data",
            "Right to Erasure: Request deletion under specified conditions",
            "Right to Withdraw Consent: Withdraw consent for processing",
            "Right to Grievance Redressal: File complaints for violations",
            "Right to Nominate: Nominate someone to exercise rights posthumously",
        ]
        for right in rights:
            doc.add_paragraph(right, style='List Bullet')

        # Review and Updates
        self._add_section(doc, "5. Review and Updates")
        doc.add_paragraph(
            "This RoPA is reviewed and updated [annually/semi-annually] or whenever processing "
            "activities change. Last reviewed: [DATE]\nNext review: [DATE]"
        )

        # Approval
        doc.add_paragraph()
        approval_para = doc.add_paragraph(
            f"Approved by: ________________ Date: ________________"
        )
        approval_para.paragraph_format.space_before = Pt(12)

        return self._save_document(doc, "Records_of_Processing_Activities.docx")

    def generate_grievance_policy(
        self,
        org_name: str,
        dpo_name: str,
        contact_email: str,
    ) -> str:
        """
        Generate a Grievance Redressal Policy per Section 13, DPDPA.

        Args:
            org_name: Organization name
            dpo_name: Data Protection Officer name
            contact_email: Contact email for grievances

        Returns:
            Path to generated document
        """
        doc = self._create_document("Grievance Redressal Policy", org_name)

        # Preamble
        self._add_section(
            doc,
            "1. Introduction",
            f"{org_name} is committed to addressing the grievances of Data Principals regarding "
            "violations of their rights under the Digital Personal Data Protection Act, 2023 (DPDPA). "
            "This policy outlines the grievance mechanism and timelines for resolution."
        )

        # Legal Framework
        self._add_section(
            doc,
            "2. Legal Framework (Section 13, DPDPA)",
            "Every entity shall implement a mechanism to acknowledge and redress grievances of "
            "Data Principals within the timelines specified by DPDPA Rules."
        )

        # What Constitutes a Grievance
        self._add_section(doc, "3. What Constitutes a Grievance")
        grievances = [
            "Unauthorized processing of personal data",
            "Denial of right to access personal data",
            "Failure to correct inaccurate or incomplete data",
            "Failure to delete personal data upon request",
            "Unauthorized transfer of personal data",
            "Failure to respond to grievance within specified timelines",
            "Any other violation of DPDPA or organizational policies",
        ]
        for grievance in grievances:
            doc.add_paragraph(grievance, style='List Bullet')

        # Filing a Grievance
        self._add_section(doc, "4. How to File a Grievance")

        self._add_subsection(doc, "4.1 Channels for Filing")
        channels = [
            f"Email: {contact_email}",
            "Physical Mail: [Office Address]",
            "Online Form: [Website URL]",
            "In Person: [Office Location]",
        ]
        for channel in channels:
            doc.add_paragraph(channel, style='List Bullet')

        self._add_subsection(doc, "4.2 Information Required")
        doc.add_paragraph("When filing a grievance, please provide:")
        info_required = [
            "Your full name and contact information",
            "Description of the grievance with dates",
            "Relevant personal data or documentation",
            "Action you expect to address the grievance",
            "Any previous communication regarding the grievance",
        ]
        for info in info_required:
            doc.add_paragraph(info, style='List Bullet')

        # Processing Timeline
        self._add_section(doc, "5. Grievance Processing Timeline")

        self._add_subsection(
            doc,
            "5.1 Acknowledgment (Within 48 hours)",
            f"We acknowledge receipt of your grievance within 48 hours. Acknowledgment will include "
            "a reference number, expected resolution timeline, and DPO contact information."
        )

        self._add_subsection(
            doc,
            "5.2 Investigation (Within 90 days)",
            "We investigate the grievance and take necessary corrective actions. You will be updated "
            "on the progress of investigation."
        )

        self._add_subsection(
            doc,
            "5.3 Resolution (Within 90 days)",
            "We provide a detailed response addressing your grievance and actions taken. If the "
            "grievance is rejected, we provide reasons for rejection."
        )

        # Escalation
        self._add_section(doc, "6. Escalation to Data Protection Board")
        doc.add_paragraph(
            "If you are not satisfied with our response, you may escalate your grievance to the "
            "Data Protection Board within 90 days of receipt of our response. Contact details:\n"
            "[Data Protection Board Address]\n"
            "[Phone Number]\n"
            "[Website URL]"
        )

        # No Retaliation
        self._add_section(doc, "7. No Retaliation Policy")
        doc.add_paragraph(
            "We do not retaliate against any Data Principal for filing a grievance in good faith. "
            "Retaliation or harassment will be treated as a serious violation."
        )

        # Data Protection Officer
        self._add_section(doc, "8. Data Protection Officer")
        dpo_info = [
            f"Name: {dpo_name}",
            f"Email: {contact_email}",
            "Phone: [Contact Number]",
            "Office Hours: [Hours]",
        ]
        for info in dpo_info:
            doc.add_paragraph(info, style='List Bullet')

        # Contact Information
        self._add_section(doc, "9. Contact Information")
        contact_details = [
            f"Organization: {org_name}",
            f"Email: {contact_email}",
            "Address: [Office Address]",
            "Phone: [Contact Number]",
            "Website: [Website URL]",
        ]
        for detail in contact_details:
            doc.add_paragraph(detail, style='List Bullet')

        # Policy Review
        self._add_section(doc, "10. Policy Review")
        doc.add_paragraph(
            "This policy is reviewed annually and updated to reflect changes in regulations, "
            "organizational practices, and feedback from Data Principals."
        )

        return self._save_document(doc, "Grievance_Redressal_Policy.docx")

    def generate_all_documents(self, org_name: str, org_details: Dict) -> Dict[str, str]:
        """
        Generate all DPDPA compliance documents at once.

        Args:
            org_name: Organization name
            org_details: Dictionary containing all details for document generation

        Returns:
            Dictionary with document names and their file paths
        """
        documents = {}

        # Privacy Policy
        documents["Privacy Policy"] = self.generate_privacy_policy(
            org_name=org_name,
            industry=org_details.get("industry", "[Industry]"),
            data_categories=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information", "Usage Data"]
            ),
            purposes=org_details.get(
                "purposes",
                ["Service Delivery", "Customer Communication", "Improvement"]
            ),
            retention_period=org_details.get("retention_period", "3 years"),
            contact_email=org_details.get("contact_email", "[contact@example.com]"),
            dpo_name=org_details.get("dpo_name", "[DPO Name]"),
        )

        # Consent Notice
        documents["Consent Notice"] = self.generate_consent_notice(
            org_name=org_name,
            purpose=org_details.get("purpose", "[Processing Purpose]"),
            data_categories=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information"]
            ),
            processors=org_details.get("processors", ["[Processor Name]"]),
            retention=org_details.get("retention_period", "3 years"),
        )

        # Data Processing Agreement
        documents["Data Processing Agreement"] = self.generate_dpa(
            controller_name=org_name,
            processor_name=org_details.get("processor_name", "[Processor Name]"),
            processing_purposes=org_details.get(
                "purposes",
                ["Service Delivery", "Data Analysis"]
            ),
            data_types=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information"]
            ),
        )

        # DPIA Report
        documents["DPIA Report"] = self.generate_dpia(
            org_name=org_name,
            project_name=org_details.get("project_name", "[Project Name]"),
            processing_description=org_details.get(
                "processing_description",
                "[Description of processing activities]"
            ),
            data_types=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information"]
            ),
            risk_assessment=org_details.get(
                "risk_assessment",
                {
                    "Unauthorized Access": "Implement encryption and access controls",
                    "Data Loss": "Implement backups and disaster recovery",
                }
            ),
        )

        # Breach Notification
        documents["Breach Notification"] = self.generate_breach_notification(
            org_name=org_name,
            breach_date=org_details.get("breach_date", "[Date]"),
            discovery_date=org_details.get("discovery_date", "[Date]"),
            description=org_details.get(
                "breach_description",
                "[Description of breach]"
            ),
            data_affected=org_details.get(
                "data_affected",
                ["Personal Identifiers", "Contact Information"]
            ),
            individuals_count=org_details.get("individuals_count", 0),
            measures_taken=org_details.get(
                "measures_taken",
                ["Secured systems", "Notified affected parties"]
            ),
        )

        # Records of Processing Activities
        documents["RoPA"] = self.generate_ropa(
            org_name=org_name,
            processing_activities=org_details.get(
                "processing_activities",
                [
                    {
                        "activity": "Customer Data Processing",
                        "purpose": "Service Delivery",
                        "legal_basis": "Consent",
                        "data_categories": "Personal Identifiers, Contact Info",
                        "data_principals": "Customers",
                        "recipients": "Internal Teams",
                        "retention": "3 years",
                        "security_measures": "Encryption, Access Control",
                        "cross_border": "No",
                    }
                ],
            ),
        )

        # Grievance Redressal Policy
        documents["Grievance Redressal Policy"] = self.generate_grievance_policy(
            org_name=org_name,
            dpo_name=org_details.get("dpo_name", "[DPO Name]"),
            contact_email=org_details.get("contact_email", "[contact@example.com]"),
        )

        return documents


def main():
    """Test the DocumentGenerator module."""
    print("Testing DocumentGenerator Module...")
    print("=" * 50)

    # Initialize generator
    generator = DocumentGenerator(output_dir="/tmp/anumati_docs/")
    print(f"Output directory: {generator.output_dir}")

    # Test organization details
    org_details = {
        "industry": "Technology",
        "data_categories": [
            "Name",
            "Email Address",
            "Phone Number",
            "Usage Data",
            "IP Address"
        ],
        "purposes": [
            "Service Delivery",
            "Customer Communication",
            "Service Improvement",
            "Compliance with Legal Obligations"
        ],
        "retention_period": "3 years or until consent withdrawn",
        "contact_email": "privacy@anumati.ai",
        "dpo_name": "Data Protection Officer",
        "purpose": "Providing AI-powered DPDPA compliance services",
        "processor_name": "Cloud Infrastructure Provider",
        "project_name": "DPDPA Compliance Portal",
        "processing_description": "Processing personal data for compliance services",
        "risk_assessment": {
            "Unauthorized Access": "Implement encryption and access controls",
            "Data Loss": "Daily backups and disaster recovery",
            "Unlawful Processing": "Regular audits and privacy impact assessments"
        },
        "processors": ["Cloud Provider A", "Service Provider B"],
        "processing_activities": [
            {
                "activity": "User Registration",
                "purpose": "Account Creation",
                "legal_basis": "Consent",
                "data_categories": "Name, Email, Password",
                "data_principals": "Website Visitors",
                "recipients": "Internal IT Team",
                "retention": "Until account deletion",
                "security_measures": "Encryption, Hashing",
                "cross_border": "No"
            },
            {
                "activity": "Service Usage Analytics",
                "purpose": "Service Improvement",
                "legal_basis": "Legitimate Interest",
                "data_categories": "Usage Data, IP Address",
                "data_principals": "Registered Users",
                "recipients": "Analytics Team",
                "retention": "2 years",
                "security_measures": "Anonymization, Access Control",
                "cross_border": "No"
            }
        ]
    }

    # Generate individual documents
    print("\nGenerating individual documents...")
    print("-" * 50)

    privacy_policy = generator.generate_privacy_policy(
        org_name="Anumati.ai",
        industry=org_details["industry"],
        data_categories=org_details["data_categories"],
        purposes=org_details["purposes"],
        retention_period=org_details["retention_period"],
        contact_email=org_details["contact_email"],
        dpo_name=org_details["dpo_name"]
    )
    print(f"✓ Privacy Policy: {privacy_policy}")

    consent_notice = generator.generate_consent_notice(
        org_name="Anumati.ai",
        purpose=org_details["purpose"],
        data_categories=org_details["data_categories"],
        processors=org_details["processors"],
        retention=org_details["retention_period"]
    )
    print(f"✓ Consent Notice: {consent_notice}")

    dpa = generator.generate_dpa(
        controller_name="Anumati.ai",
        processor_name=org_details["processor_name"],
        processing_purposes=org_details["purposes"],
        data_types=org_details["data_categories"]
    )
    print(f"✓ DPA: {dpa}")

    dpia = generator.generate_dpia(
        org_name="Anumati.ai",
        project_name=org_details["project_name"],
        processing_description=org_details["processing_description"],
        data_types=org_details["data_categories"],
        risk_assessment=org_details["risk_assessment"]
    )
    print(f"✓ DPIA Report: {dpia}")

    breach = generator.generate_breach_notification(
        org_name="Anumati.ai",
        breach_date="01-03-2026",
        discovery_date="02-03-2026",
        description="Unauthorized access to customer database",
        data_affected=org_details["data_categories"],
        individuals_count=1000,
        measures_taken=["Secured systems", "Notified affected parties", "Enhanced monitoring"]
    )
    print(f"✓ Breach Notification: {breach}")

    ropa = generator.generate_ropa(
        org_name="Anumati.ai",
        processing_activities=org_details["processing_activities"]
    )
    print(f"✓ RoPA: {ropa}")

    grievance = generator.generate_grievance_policy(
        org_name="Anumati.ai",
        dpo_name=org_details["dpo_name"],
        contact_email=org_details["contact_email"]
    )
    print(f"✓ Grievance Policy: {grievance}")

    # Generate all documents at once
    print("\n" + "=" * 50)
    print("Generating all documents...")
    print("-" * 50)

    all_docs = generator.generate_all_documents(
        org_name="Anumati.ai",
        org_details=org_details
    )

    for doc_name, doc_path in all_docs.items():
        print(f"✓ {doc_name}: {doc_path}")

    print("\n" + "=" * 50)
    print(f"All documents generated successfully in: {generator.output_dir}")
    print("=" * 50)


if __name__ == "__main__":
    main()
