"""
DPDPA Compliance Document Generator
Generates rule-based DPDPA compliance documents as DOCX files.
Part of the Svikruti.ai tool.
"""

import os
import re
import tempfile
from datetime import datetime
from typing import List, Dict, Optional
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


DISCLAIMER_TEXT = (
    "This is a template generated by Svikruti.ai. It does not constitute legal advice "
    "and must be reviewed and approved by qualified legal counsel before use."
)


class DocumentGenerator:
    """Generate DPDPA-compliant documents in DOCX format."""

    def __init__(self, output_dir: Optional[str] = None):
        """
        Initialize the document generator.

        Args:
            output_dir: Directory to save generated documents. If not provided,
                a unique per-instance temporary directory is created so that
                concurrent sessions never share paths or overwrite each other.
        """
        if output_dir:
            self.output_dir = output_dir
            os.makedirs(output_dir, exist_ok=True)
        else:
            self.output_dir = tempfile.mkdtemp(prefix="svikruti_docs_")

        self.generation_date = datetime.now().strftime("%d-%m-%Y")

    @staticmethod
    def _slugify(value: str) -> str:
        """Convert an organization name to a filesystem-safe slug."""
        slug = re.sub(r"[^A-Za-z0-9]+", "_", value or "").strip("_")
        return slug or "org"

    def _create_document(self, title: str, org_name: str) -> Document:
        """
        Create a new document with standard formatting.

        Args:
            title: Document title
            org_name: Organization name

        Returns:
            Document object with header, title, and footer
        """
        doc = Document()

        # Set up header with organization name and template disclaimer
        section = doc.sections[0]
        header = section.header
        header_para = header.paragraphs[0]
        header_para.text = f"{org_name} | Template generated by Svikruti.ai - not legal advice"
        header_para.style = 'Header'

        # Set up footer with generation info and template disclaimer
        footer = section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = (
            f"Generated by Svikruti.ai | {self.generation_date} | "
            "Template only - must be reviewed by qualified legal counsel; not legal advice."
        )
        footer_para.style = 'Footer'
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add title
        title_para = doc.add_paragraph()
        title_run = title_para.add_run(title)
        title_run.font.size = Pt(18)
        title_run.font.bold = True
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add generation date
        date_para = doc.add_paragraph()
        date_run = date_para.add_run(f"Generated on: {self.generation_date}")
        date_run.font.size = Pt(10)
        date_run.font.italic = True
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add prominent disclaimer
        disclaimer_para = doc.add_paragraph()
        disclaimer_run = disclaimer_para.add_run(DISCLAIMER_TEXT)
        disclaimer_run.font.size = Pt(9)
        disclaimer_run.font.italic = True
        disclaimer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()  # Spacing
        return doc

    def _add_section(self, doc: Document, heading: str, content: str = None) -> None:
        """
        Add a section with heading and optional content.

        Args:
            doc: Document object
            heading: Section heading
            content: Optional section content
        """
        heading_para = doc.add_paragraph(heading, style='Heading 1')
        heading_para.paragraph_format.space_before = Pt(12)
        heading_para.paragraph_format.space_after = Pt(6)

        if content:
            content_para = doc.add_paragraph(content)
            content_para.paragraph_format.space_after = Pt(6)

    def _add_subsection(self, doc: Document, heading: str, content: str = None) -> None:
        """
        Add a subsection with heading and optional content.

        Args:
            doc: Document object
            heading: Subsection heading
            content: Optional section content
        """
        heading_para = doc.add_paragraph(heading, style='Heading 2')
        heading_para.paragraph_format.space_before = Pt(8)
        heading_para.paragraph_format.space_after = Pt(4)

        if content:
            content_para = doc.add_paragraph(content)
            content_para.paragraph_format.space_after = Pt(4)

    def _save_document(self, doc: Document, base_name: str, org_name: str = "") -> str:
        """
        Save document to a collision-safe file path.

        The filename embeds the organization slug and a timestamp so that
        concurrent generations for different organizations (or repeated
        generations for the same organization) never overwrite each other.

        Args:
            doc: Document object
            base_name: Base name of the file (without extension)
            org_name: Organization name (used for the filename slug)

        Returns:
            Full file path
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        filename = f"{base_name}_{self._slugify(org_name)}_{timestamp}.docx"
        filepath = os.path.join(self.output_dir, filename)
        doc.save(filepath)
        return filepath

    def generate_privacy_policy(
        self,
        org_name: str,
        industry: str,
        data_categories: List[str],
        purposes: List[str],
        retention_period: str,
        contact_email: str,
        dpo_name: str,
    ) -> str:
        """
        Generate a DPDPA-compliant Privacy Policy.

        Args:
            org_name: Organization name
            industry: Industry/sector
            data_categories: List of data categories collected
            purposes: List of processing purposes
            retention_period: Data retention period
            contact_email: Contact email for inquiries
            dpo_name: Data Protection Officer name

        Returns:
            Path to generated document
        """
        doc = self._create_document("Privacy Policy", org_name)

        # Introduction
        self._add_section(
            doc,
            "1. Introduction",
            f"{org_name} (hereinafter 'Data Fiduciary' or 'We') respects your privacy and is "
            "committed to protecting your personal data. This Privacy Policy explains how we collect, "
            "process, and protect your data in compliance with the Digital Personal Data Protection "
            "Act, 2023 (DPDPA)."
        )

        # Definitions
        self._add_section(doc, "2. Definitions")
        defs = [
            "Personal Data: Any data about an individual who is identifiable by or in relation "
            "to such data.",
            "Processing: Any operation performed on personal data such as collection, recording, "
            "storage, adaptation, retrieval, consultation, use, transmission, or erasure.",
            "Data Principal: The individual to whom the personal data relates.",
            "Data Fiduciary: The person who, alone or with others, determines the purpose and "
            "means of processing personal data.",
            "Data Processor: A person who processes personal data on behalf of the Data Fiduciary "
            "under a valid contract (Section 8(2), DPDPA).",
            "Cross-Border Transfer: Transfer of personal data outside India.",
        ]
        for definition in defs:
            doc.add_paragraph(definition, style='List Bullet')

        # Data We Collect
        self._add_section(doc, "3. Data We Collect")
        self._add_subsection(doc, "3.1 Categories of Data")
        doc.add_paragraph(
            "We collect the following categories of personal data from Data Principals:"
        )
        for category in data_categories:
            doc.add_paragraph(category, style='List Bullet')

        self._add_subsection(
            doc,
            "3.2 Sources of Data",
            "We collect data directly from you through: online forms, website interactions, "
            "customer service interactions, purchases, registrations, and communications."
        )

        # Purpose of Processing
        self._add_section(doc, "4. Purpose of Processing (Section 4, DPDPA)")
        doc.add_paragraph(
            "We process your personal data only for lawful purposes, either with your consent "
            "or for certain legitimate uses, for the following purposes:"
        )
        for idx, purpose in enumerate(purposes, 1):
            doc.add_paragraph(f"Purpose {idx}: {purpose}", style='List Bullet')

        # Legal Basis
        self._add_section(doc, "5. Legal Basis for Processing (Sections 6 and 7, DPDPA)")
        self._add_subsection(doc, "5.1 Consent (Section 6)")
        doc.add_paragraph(
            "Processing is based on your consent, which is free, specific, informed, "
            "unconditional, and unambiguous, given by a clear affirmative action. You have the "
            "right to withdraw consent at any time, and withdrawing consent is as easy as giving "
            "it (Section 6(4)-(6), DPDPA)."
        )

        self._add_subsection(doc, "5.2 Certain Legitimate Uses (Section 7)")
        doc.add_paragraph(
            "[TO BE COMPLETED: where applicable, describe processing under Section 7, DPDPA, "
            "such as data you voluntarily provide for a specified purpose, compliance with law "
            "or a court order, medical emergencies, or employment-related purposes.]"
        )

        self._add_subsection(doc, "5.3 Legal Obligation")
        doc.add_paragraph(
            "[TO BE COMPLETED: where applicable, describe processing necessary for compliance "
            "with any law for the time being in force, which is a legitimate use under "
            "Section 7, DPDPA.]"
        )

        # Data Principal Rights
        self._add_section(doc, "6. Your Rights as a Data Principal (Sections 11-14, DPDPA)")

        self._add_subsection(
            doc,
            "6.1 Right to Access Information (Section 11)",
            "You have the right to obtain a summary of your personal data being processed by us "
            "and the processing activities undertaken, along with the identities of Data "
            f"Fiduciaries and Data Processors with whom it has been shared. Submit a written "
            f"request to {contact_email}."
        )

        self._add_subsection(
            doc,
            "6.2 Right to Correction, Completion and Updating (Section 12)",
            "You may request correction of inaccurate or misleading personal data, completion of "
            f"incomplete data, and updating of your personal data. Submit requests to "
            f"{contact_email}."
        )

        self._add_subsection(
            doc,
            "6.3 Right to Erasure (Section 12 read with Section 8(7))",
            "You can request erasure of your personal data. We will erase personal data when you "
            "withdraw consent or when the specified purpose is no longer being served, unless "
            "retention is necessary for compliance with any law for the time being in force."
        )

        self._add_subsection(
            doc,
            "6.4 Right to Grievance Redressal (Section 13)",
            "You have the right to readily available means of grievance redressal for any act or "
            "omission regarding our obligations or your rights under DPDPA. Contact our DPO, and "
            "if unresolved, you may approach the Data Protection Board of India."
        )

        self._add_subsection(
            doc,
            "6.5 Right to Nominate (Section 14)",
            "You may nominate another individual to exercise your rights in the event of your "
            "death or incapacity."
        )

        # Data Retention
        self._add_section(
            doc,
            "7. Data Retention",
            f"We retain your personal data for {retention_period}. After this period, or once "
            "the specified purpose is no longer being served or consent is withdrawn, data is "
            "securely erased (Section 8(7), DPDPA) unless retention is required by law."
        )

        # Security Measures
        self._add_section(doc, "8. Security Safeguards (Section 8(5), DPDPA)")
        security_measures = [
            "Encryption of data in transit and at rest using industry-standard encryption",
            "Regular security audits and penetration testing",
            "Access controls and authentication mechanisms",
            "Employee training on data protection and privacy practices",
            "Incident response procedures for data breaches",
            "Physical security measures for data centers",
        ]
        for measure in security_measures:
            doc.add_paragraph(measure, style='List Bullet')

        # Cross-Border Transfers
        self._add_section(doc, "9. Cross-Border Data Transfers (Section 16, DPDPA)")
        doc.add_paragraph(
            "Personal data may be transferred outside India, except to any country or territory "
            "restricted by notification of the Central Government under Section 16, DPDPA. "
            "Stricter requirements under other applicable laws (for example, RBI data "
            "localisation directions for payment system data) continue to apply. As a matter of "
            "good practice, we put in place contractual safeguards with overseas recipients of "
            "personal data."
        )

        # Children's Data
        self._add_section(doc, "10. Processing of Children's Data (Section 9, DPDPA)")
        doc.add_paragraph(
            "We do not knowingly collect personal data from children (individuals under 18 "
            "years) without verifiable consent of a parent or lawful guardian. We do not "
            "undertake tracking or behavioural monitoring of children, or targeted advertising "
            "directed at children. If we become aware that we have collected data from a child "
            "without verifiable parental consent, we will delete it immediately."
        )

        # Grievance Redressal
        self._add_section(doc, "11. Grievance Redressal Mechanism (Section 13 read with Section 8(10), DPDPA)")
        doc.add_paragraph(
            f"Data Protection Officer / Contact Person (Section 8(9), DPDPA): {dpo_name}\n"
            f"Email: {contact_email}\n\n"
            "We acknowledge grievances within 48 hours and resolve them within 90 days. "
            "If not satisfied, you may approach the Data Protection Board of India."
        )

        # Changes to Policy
        self._add_section(
            doc,
            "12. Changes to This Policy",
            "We may update this Privacy Policy periodically. Major changes will be communicated "
            "to you via email or prominent notice on our website."
        )

        # Contact Information
        self._add_section(doc, "13. Contact Information")
        contact_info = [
            f"Organization: {org_name}",
            f"Industry: {industry}",
            f"Email: {contact_email}",
            f"Data Protection Officer: {dpo_name}",
        ]
        for info in contact_info:
            doc.add_paragraph(info)

        # DPDPA Compliance Reference
        doc.add_paragraph()
        compliance_ref = doc.add_paragraph(
            "This Privacy Policy template is prepared with reference to the Digital Personal "
            "Data Protection Act, 2023 and associated Rules. " + DISCLAIMER_TEXT
        )
        compliance_ref.paragraph_format.space_before = Pt(12)

        return self._save_document(doc, "Privacy_Policy", org_name)

    def generate_consent_notice(
        self,
        org_name: str,
        purpose: str = None,
        data_categories: List[str] = None,
        processors: List[str] = None,
        retention: str = None,
        consent_scope: str = None,
        data_types: List[str] = None,
        retention_period: str = None,
    ) -> str:
        """
        Generate an itemized Consent Notice per Sections 5 and 6, DPDPA (read with the
        DPDP Rules, 2025).

        Args:
            org_name: Organization name
            purpose: Purpose of processing
            data_categories: Categories of data to be processed
            processors: List of processors who will handle data
            retention: Data retention period
            consent_scope: Alias for purpose (app.py compatibility)
            data_types: Alias for data_categories (app.py compatibility)
            retention_period: Alias for retention (app.py compatibility)

        Returns:
            Path to generated document
        """
        purpose = purpose or consent_scope or "[TO BE COMPLETED: purpose of processing]"
        data_categories = data_categories or data_types or []
        processors = processors or []
        retention = retention or retention_period or "[TO BE COMPLETED: retention period]"

        doc = self._create_document("Consent Notice", org_name)

        # Introduction
        self._add_section(
            doc,
            "Consent Notice - Sections 5 and 6, DPDPA (read with DPDP Rules, 2025)",
            f"{org_name} requests your free, specific, informed, unconditional, and unambiguous "
            "consent, given by a clear affirmative action, to process your personal data as "
            "detailed below. This notice is available in English and, on request, in any of the "
            "22 languages specified in the Eighth Schedule to the Constitution of India "
            "(Section 5(3), DPDPA)."
        )

        # Consent Requirements
        self._add_section(doc, "1. Consent Requirements (Section 6, DPDPA)")
        requirements = [
            "Free: You are under no obligation to provide consent.",
            "Specific: Consent is requested separately for each purpose.",
            "Informed: You are fully informed about data processing practices.",
            "Unconditional: Your consent is not conditional on accepting irrelevant conditions.",
            "Unambiguous: Consent is given by a clear affirmative action, signifying agreement "
            "to processing for the specified purpose.",
        ]
        for req in requirements:
            doc.add_paragraph(req, style='List Bullet')

        # Data Categories
        self._add_section(doc, "2. Categories of Personal Data We Collect")
        if data_categories:
            for category in data_categories:
                doc.add_paragraph(category, style='List Bullet')
        else:
            doc.add_paragraph("[TO BE COMPLETED: categories of personal data]", style='List Bullet')

        # Purpose of Processing
        self._add_section(doc, "3. Purpose of Processing")
        doc.add_paragraph(f"Purpose: {purpose}")
        doc.add_paragraph(
            "Processing is limited to this specified purpose. If we wish to use your data "
            "for a different purpose, we will seek separate consent."
        )

        # Data Processors
        self._add_section(doc, "4. Data Processors (Section 8(2), DPDPA)")
        doc.add_paragraph(
            "The following entities may process your data on our behalf under valid "
            "data processing contracts:"
        )
        if processors:
            for processor in processors:
                doc.add_paragraph(processor, style='List Bullet')
        else:
            doc.add_paragraph("[TO BE COMPLETED: list of data processors]", style='List Bullet')

        # Data Retention
        self._add_section(doc, "5. Data Retention Period")
        doc.add_paragraph(
            f"Your personal data will be retained for: {retention}\n"
            "After this period, or once the specified purpose is no longer being served or "
            "consent is withdrawn, your data will be securely erased (Section 8(7), DPDPA) "
            "unless we are legally required to retain it."
        )

        # Your Rights
        self._add_section(doc, "6. Your Rights (Sections 11-14, DPDPA)")
        rights = [
            "Right to Access Information (Section 11): Obtain a summary of your personal data "
            "and processing activities.",
            "Right to Correction, Completion, Updating and Erasure (Section 12): Correct "
            "inaccurate or incomplete data and request erasure.",
            "Right to Withdraw Consent (Section 6(4)): Withdraw your consent at any time; "
            "withdrawal is as easy as giving consent.",
            "Right to Grievance Redressal (Section 13): Raise a grievance with our DPO/contact "
            "person, and thereafter complain to the Data Protection Board of India.",
            "Right to Nominate (Section 14): Nominate an individual to exercise your rights in "
            "the event of death or incapacity.",
        ]
        for right in rights:
            doc.add_paragraph(right, style='List Bullet')

        # Withdrawal of Consent
        self._add_section(doc, "7. How to Withdraw Consent (Section 6(4)-(6), DPDPA)")
        doc.add_paragraph(
            "You can withdraw your consent at any time, with ease comparable to that with which "
            "consent was given, by:\n"
            "- Sending an email to [TO BE COMPLETED: contact email]\n"
            "- Submitting a written request to [TO BE COMPLETED: office address]\n"
            "- Using the 'Unsubscribe' link in communications from us\n\n"
            "Withdrawal will not affect the validity of processing done before withdrawal."
        )

        # Consent Statement
        self._add_section(doc, "8. Consent Statement")
        doc.add_paragraph(
            "By providing your signature below or clicking 'I Agree' digitally, you confirm that:"
        )
        confirmations = [
            "You have read and understood this Consent Notice.",
            "You have received clear information about our data processing practices.",
            "You freely and voluntarily provide consent to the processing described above.",
            "You understand you can withdraw consent at any time without penalty.",
        ]
        for confirmation in confirmations:
            doc.add_paragraph(confirmation, style='List Bullet')

        # Sign-off Section
        doc.add_paragraph()
        sign_off = doc.add_paragraph("Signature/Consent: ________________     Date: ________________")
        sign_off.paragraph_format.space_before = Pt(12)

        return self._save_document(doc, "Consent_Notice", org_name)

    def generate_dpa(
        self,
        controller_name: str = None,
        processor_name: str = None,
        processing_purposes: List[str] = None,
        data_types: List[str] = None,
        data_controller: str = None,
        data_processor: str = None,
        processing_activities: List[str] = None,
    ) -> str:
        """
        Generate a Data Processing Agreement (DPA) template per Section 8(2), DPDPA.

        Args:
            controller_name: Name of the Data Fiduciary (legacy parameter name)
            processor_name: Name of the Data Processor
            processing_purposes: List of processing purposes
            data_types: Types of data to be processed
            data_controller: Alias for controller_name (app.py compatibility)
            data_processor: Alias for processor_name (app.py compatibility)
            processing_activities: Alias for processing_purposes (app.py compatibility)

        Returns:
            Path to generated document
        """
        fiduciary_name = controller_name or data_controller or "[TO BE COMPLETED: Data Fiduciary name]"
        processor = processor_name or data_processor or "[TO BE COMPLETED: Data Processor name]"
        processing_purposes = processing_purposes or processing_activities or []
        data_types = data_types or []

        doc = self._create_document("Data Processing Agreement", fiduciary_name)

        # Preamble
        self._add_section(doc, "1. Definitions")
        defs = [
            f"Data Fiduciary: {fiduciary_name}",
            f"Data Processor: {processor}",
            "Personal Data: Any data about an individual who is identifiable by or in relation "
            "to such data.",
            "Processing: Any operation performed on personal data.",
            "Data Principal: The individual to whom the personal data relates.",
        ]
        for definition in defs:
            doc.add_paragraph(definition, style='List Bullet')

        # Scope
        self._add_section(doc, "2. Scope and Objectives")
        self._add_subsection(
            doc,
            "2.1 Purpose",
            "This Agreement defines the terms under which the Data Processor shall process "
            "personal data on behalf of the Data Fiduciary under a valid contract as required "
            "by Section 8(2), DPDPA."
        )

        self._add_subsection(doc, "2.2 Processing Purposes")
        if processing_purposes:
            for purpose in processing_purposes:
                doc.add_paragraph(purpose, style='List Bullet')
        else:
            doc.add_paragraph("[TO BE COMPLETED: processing purposes]", style='List Bullet')

        self._add_subsection(doc, "2.3 Data Types")
        if data_types:
            for data_type in data_types:
                doc.add_paragraph(data_type, style='List Bullet')
        else:
            doc.add_paragraph("[TO BE COMPLETED: data types]", style='List Bullet')

        # Processing Instructions
        self._add_section(doc, "3. Processing Instructions (Section 8(2), DPDPA)")
        self._add_subsection(
            doc,
            "3.1 Authority",
            "The Data Processor shall process personal data only on documented instructions "
            "from the Data Fiduciary."
        )
        self._add_subsection(
            doc,
            "3.2 Personnel Confidentiality",
            "The Data Processor shall ensure that any person authorized to process personal data "
            "commits to confidentiality."
        )
        self._add_subsection(
            doc,
            "3.3 Limitations",
            "The Data Processor shall not process data for purposes other than those specified "
            "in this Agreement without prior written consent from the Data Fiduciary."
        )

        # Security Measures
        self._add_section(doc, "4. Security Safeguards (Section 8(5), DPDPA)")
        measures = [
            "Encryption of data in transit and at rest",
            "Access control and authentication mechanisms",
            "Regular security audits and assessments",
            "Secure deletion and destruction procedures",
            "Business continuity and disaster recovery plans",
            "Regular staff training on data protection",
        ]
        for measure in measures:
            doc.add_paragraph(measure, style='List Bullet')

        # Sub-processors
        self._add_section(doc, "5. Sub-processors")
        doc.add_paragraph(
            "The Data Processor shall not engage sub-processors without prior written "
            "authorization from the Data Fiduciary. The Data Processor remains liable to the "
            "Data Fiduciary for the performance of sub-processors."
        )

        # Audit Rights
        self._add_section(doc, "6. Audit Rights")
        doc.add_paragraph(
            "The Data Fiduciary has the right to audit the Data Processor's compliance with this "
            "Agreement. The Data Processor shall provide assistance and access to relevant "
            "records, systems, and personnel for such audits."
        )

        # Data Breach Notification
        self._add_section(doc, "7. Personal Data Breach Notification (Section 8(6), DPDPA read with DPDP Rules, 2025)")
        doc.add_paragraph(
            "The Data Processor shall notify the Data Fiduciary without undue delay (and in any "
            "event within 24 hours) upon becoming aware of any personal data breach, so that the "
            "Data Fiduciary can give immediate intimation of the breach to the Data Protection "
            "Board of India and to each affected Data Principal, and submit the detailed report "
            "to the Board within 72 hours, as required by Section 8(6), DPDPA and the DPDP "
            "Rules, 2025. The notification shall include: nature of the breach, data affected, "
            "number of individuals, likely consequences, and measures taken to address the breach."
        )

        # Data Principal Rights
        self._add_section(doc, "8. Data Principal Rights (Sections 11-14, DPDPA)")
        doc.add_paragraph(
            "The Data Processor shall assist the Data Fiduciary in responding to Data Principal "
            "requests for access to information (Section 11), correction, completion, updating "
            "and erasure (Section 12), grievance redressal (Section 13), and nomination "
            "(Section 14) within stipulated timelines."
        )

        # Return or Deletion of Data
        self._add_section(doc, "9. Return or Deletion of Data (Section 8(7), DPDPA)")
        doc.add_paragraph(
            "Upon termination of this Agreement, the Data Processor shall, at the Data "
            "Fiduciary's choice: (a) return all personal data to the Data Fiduciary, or "
            "(b) securely erase all personal data and provide written confirmation of erasure."
        )

        # Liability
        self._add_section(doc, "10. Liability and Indemnification")
        doc.add_paragraph(
            "The Data Processor shall indemnify the Data Fiduciary against any claims, damages, "
            "or costs arising from the Data Processor's violation of this Agreement or "
            "applicable data protection laws."
        )

        # Term and Termination
        self._add_section(doc, "11. Term and Termination")
        self._add_subsection(doc, "11.1 Effective Date")
        doc.add_paragraph("[TO BE COMPLETED: effective date]")

        self._add_subsection(doc, "11.2 Duration")
        doc.add_paragraph("[TO BE COMPLETED: duration, or 'Until terminated by either party']")

        self._add_subsection(doc, "11.3 Termination Rights")
        doc.add_paragraph(
            "Either party may terminate this Agreement with [TO BE COMPLETED: notice period, "
            "e.g. 30 days] written notice. Upon termination, the Data Processor shall cease "
            "processing immediately."
        )

        # Signatures
        doc.add_paragraph()
        sig_section = doc.add_paragraph("Signatures:")
        sig_section.paragraph_format.space_before = Pt(12)

        sig_table = doc.add_table(rows=3, cols=2)
        sig_table.autofit = False
        sig_table.allow_autofit = False

        sig_cells = sig_table.rows[0].cells
        sig_cells[0].text = "Data Fiduciary"
        sig_cells[1].text = f"Name: {fiduciary_name}"

        sig_cells = sig_table.rows[1].cells
        sig_cells[0].text = "Signature: ____________________"
        sig_cells[1].text = f"Date: ____________________"

        sig_cells = sig_table.rows[2].cells
        sig_cells[0].text = "Data Processor"
        sig_cells[1].text = f"Name: {processor}"

        return self._save_document(doc, "Data_Processing_Agreement", fiduciary_name)

    def generate_dpia(
        self,
        org_name: str,
        project_name: str = None,
        processing_description: str = None,
        data_types: List[str] = None,
        risk_assessment: Dict[str, str] = None,
        processing_name: str = None,
        data_subjects: List[str] = None,
    ) -> str:
        """
        Generate a Data Protection Impact Assessment (DPIA) Report.

        Args:
            org_name: Organization name
            project_name: Name of the project/processing activity
            processing_description: Description of the processing
            data_types: Types of data involved
            risk_assessment: Dictionary mapping risk factors to either a mitigation
                string, or a dict with keys 'likelihood', 'impact', 'level', 'mitigation'
            processing_name: Alias for project_name (app.py compatibility)
            data_subjects: Data Principals covered (app.py compatibility)

        Returns:
            Path to generated document
        """
        project_name = project_name or processing_name or "[TO BE COMPLETED: project name]"
        processing_description = processing_description or "[TO BE COMPLETED: description of processing]"
        data_types = data_types or []
        risk_assessment = risk_assessment or {}

        doc = self._create_document("Data Protection Impact Assessment Report", org_name)

        # Executive Summary
        self._add_section(
            doc,
            "1. Executive Summary",
            f"This DPIA assesses the data protection risks associated with the '{project_name}' "
            "processing activity and recommends mitigation measures to ensure compliance with "
            "DPDPA. Periodic DPIA is a statutory obligation for Significant Data Fiduciaries "
            "under Section 10, DPDPA, and recommended good practice for all Data Fiduciaries."
        )

        # Project Overview
        self._add_section(doc, "2. Project Overview")
        self._add_subsection(doc, "2.1 Project Name")
        doc.add_paragraph(project_name)

        self._add_subsection(doc, "2.2 Organization")
        doc.add_paragraph(org_name)

        self._add_subsection(doc, "2.3 Processing Description")
        doc.add_paragraph(processing_description)

        self._add_subsection(doc, "2.4 Data Types Involved")
        if data_types:
            for data_type in data_types:
                doc.add_paragraph(data_type, style='List Bullet')
        else:
            doc.add_paragraph("[TO BE COMPLETED: data types involved]", style='List Bullet')

        self._add_subsection(doc, "2.5 Data Principals Covered")
        if data_subjects:
            for principal_group in data_subjects:
                doc.add_paragraph(principal_group, style='List Bullet')
        else:
            doc.add_paragraph("[TO BE COMPLETED: categories of Data Principals]", style='List Bullet')

        # Legal Basis
        self._add_section(doc, "3. Legal Basis for Processing")
        doc.add_paragraph(
            "Consent (Section 6, DPDPA) or certain legitimate uses (Section 7, DPDPA), "
            "as applicable to each processing purpose."
        )

        # Risk Assessment Matrix
        self._add_section(doc, "4. Risk Assessment Matrix")
        doc.add_paragraph(
            "Risk Level = Likelihood x Impact\n"
            "Low: 1-2 | Medium: 3-6 | High: 8-9 | Critical: 10-12"
        )

        # Create risk table dynamically sized to the actual risks
        if risk_assessment:
            risk_table = doc.add_table(rows=len(risk_assessment) + 1, cols=4)
            risk_table.style = 'Light Grid Accent 1'

            hdr_cells = risk_table.rows[0].cells
            hdr_cells[0].text = "Risk Factor"
            hdr_cells[1].text = "Likelihood"
            hdr_cells[2].text = "Impact"
            hdr_cells[3].text = "Level"

            for row_idx, (risk_name, details) in enumerate(risk_assessment.items(), 1):
                cells = risk_table.rows[row_idx].cells
                cells[0].text = str(risk_name)
                if isinstance(details, dict):
                    cells[1].text = str(details.get("likelihood", "TBD"))
                    cells[2].text = str(details.get("impact", "TBD"))
                    cells[3].text = str(details.get("level", "TBD"))
                else:
                    cells[1].text = "TBD"
                    cells[2].text = "TBD"
                    cells[3].text = "TBD"
        else:
            doc.add_paragraph("[TO BE COMPLETED: identified risks and their assessment]")

        # Mitigation Measures
        self._add_section(doc, "5. Mitigation Measures")
        doc.add_paragraph(
            "The following measures shall be implemented to mitigate identified risks:"
        )
        if risk_assessment:
            for idx, (risk_name, details) in enumerate(risk_assessment.items(), 1):
                if isinstance(details, dict):
                    mitigation = details.get("mitigation", "[TO BE COMPLETED: mitigation measures]")
                else:
                    mitigation = details
                self._add_subsection(doc, f"5.{idx} {risk_name}")
                doc.add_paragraph(f"Mitigation: {mitigation}")
        else:
            doc.add_paragraph("[TO BE COMPLETED: mitigation measures for each identified risk]")

        # Residual Risk Assessment
        self._add_section(doc, "6. Residual Risk Assessment")
        doc.add_paragraph(
            "After implementation of mitigation measures:\n"
            "[TO BE COMPLETED: assess whether residual risks are acceptable and consistent "
            "with DPDPA compliance]"
        )

        # Recommendations
        self._add_section(doc, "7. Recommendations")
        recommendations = [
            "Implement encryption for data in transit and at rest",
            "Establish regular security audits and penetration testing",
            "Provide data protection training to all personnel",
            "Implement access controls and authentication mechanisms",
            "Establish incident response procedures for data breaches",
            "Monitor and review processing activities regularly",
        ]
        for rec in recommendations:
            doc.add_paragraph(rec, style='List Bullet')

        # Approval and Sign-off
        self._add_section(doc, "8. Sign-off")
        doc.add_paragraph(
            "Data Protection Officer: ________________ Date: ________________\n"
            "Project Lead: ________________ Date: ________________\n"
            "Organization Head: ________________ Date: ________________"
        )

        return self._save_document(doc, "DPIA_Report", org_name)

    def generate_breach_notification(
        self,
        org_name: str,
        breach_date: str = None,
        discovery_date: str = None,
        description: str = None,
        data_affected=None,
        individuals_count: int = None,
        measures_taken: List[str] = None,
        breach_description: str = None,
        individuals_affected: int = None,
    ) -> str:
        """
        Generate a Data Breach Notification document per Section 8(6), DPDPA
        read with the DPDP Rules, 2025.

        Args:
            org_name: Organization name
            breach_date: Date when breach occurred
            discovery_date: Date when breach was discovered
            description: Description of the breach
            data_affected: Categories of data affected (list or single string)
            individuals_count: Number of Data Principals affected
            measures_taken: List of remedial measures taken
            breach_description: Alias for description (app.py compatibility)
            individuals_affected: Alias for individuals_count (app.py compatibility)

        Returns:
            Path to generated document
        """
        description = description or breach_description or "[TO BE COMPLETED: description of the breach]"
        breach_date = breach_date or "[TO BE COMPLETED: breach date]"
        discovery_date = discovery_date or "[TO BE COMPLETED: discovery date]"
        if individuals_count is None:
            individuals_count = individuals_affected
        if data_affected is None:
            data_affected = ["[TO BE COMPLETED: data categories affected]"]
        elif isinstance(data_affected, str):
            data_affected = [data_affected]
        measures_taken = measures_taken or ["[TO BE COMPLETED: remedial measures taken]"]
        affected_count_text = (
            str(individuals_count) if individuals_count is not None
            else "[TO BE COMPLETED: number of Data Principals affected]"
        )

        doc = self._create_document("Data Breach Notification", org_name)

        # Part 1: Notification to Data Protection Board of India
        self._add_section(doc, "PART 1: NOTIFICATION TO THE DATA PROTECTION BOARD OF INDIA")

        self._add_section(
            doc,
            "1. Notification Details (Section 8(6), DPDPA read with DPDP Rules, 2025)"
        )
        doc.add_paragraph(
            "On becoming aware of a personal data breach, the Data Fiduciary must give "
            "immediate intimation of the breach to the Data Protection Board of India and to "
            "each affected Data Principal, and must submit a detailed report to the Board "
            "within 72 hours (or such longer period as the Board may allow on request)."
        )

        notification_details = [
            f"Organization: {org_name}",
            f"Breach Date: {breach_date}",
            f"Discovery Date: {discovery_date}",
            f"Reporting Date: {self.generation_date}",
        ]
        for detail in notification_details:
            doc.add_paragraph(detail, style='List Bullet')

        self._add_section(doc, "2. Breach Description")
        doc.add_paragraph(description)

        self._add_section(doc, "3. Data Affected")
        for data_cat in data_affected:
            doc.add_paragraph(data_cat, style='List Bullet')

        self._add_section(
            doc,
            "4. Number of Data Principals Affected",
            f"Approximately {affected_count_text} Data Principals have been affected."
        )

        self._add_section(doc, "5. Nature and Consequences of the Breach")
        doc.add_paragraph(
            "The breach has resulted in:\n"
            "- Unauthorized access to personal data\n"
            "- [TO BE COMPLETED: risk of identity theft, financial loss, or other consequences]\n"
            "- [TO BE COMPLETED: impact assessment details]"
        )

        self._add_section(doc, "6. Measures Taken to Address the Breach")
        for measure in measures_taken:
            doc.add_paragraph(measure, style='List Bullet')

        self._add_section(doc, "7. Measures to Mitigate Harm")
        doc.add_paragraph(
            "- Immediate intimation to affected Data Principals\n"
            "- Offer of credit monitoring services\n"
            "- Enhanced security measures\n"
            "- [TO BE COMPLETED: additional preventive measures]"
        )

        # Part 2: Notification to Data Principals
        doc.add_page_break()
        self._add_section(doc, "PART 2: NOTIFICATION TO DATA PRINCIPALS")

        self._add_section(
            doc,
            "1. Notice to Affected Individuals",
            f"To the Data Principals affected by the personal data breach at {org_name}:"
        )

        self._add_section(doc, "2. What Happened")
        doc.add_paragraph(
            f"On {breach_date}, we identified a personal data breach affecting your personal "
            f"information: {description}"
        )

        self._add_section(doc, "3. What Information Was Affected")
        for data_cat in data_affected:
            doc.add_paragraph(data_cat, style='List Bullet')

        self._add_section(doc, "4. What We Are Doing")
        doc.add_paragraph(
            "- Securing the breach and preventing further unauthorized access\n"
            "- Investigating the incident thoroughly\n"
            "- Implementing additional security measures\n"
            "- Reporting to the Data Protection Board of India and, where relevant, law "
            "enforcement authorities"
        )

        self._add_section(doc, "5. What You Can Do")
        actions = [
            "Review your personal information for suspicious activity",
            "Monitor your credit reports for unauthorized transactions",
            "Change passwords for online accounts",
            "Consider identity theft protection services",
            "Report any suspected fraud to relevant authorities",
        ]
        for action in actions:
            doc.add_paragraph(action, style='List Bullet')

        self._add_section(doc, "6. Contact Information for Questions")
        doc.add_paragraph(
            "If you have questions about this breach or our response, please contact:\n"
            "[TO BE COMPLETED: contact name]\n"
            "[TO BE COMPLETED: contact email]\n"
            "[TO BE COMPLETED: contact phone]\n"
            "Data Protection Officer: [TO BE COMPLETED: DPO name]\n"
            "Email: [TO BE COMPLETED: DPO email]"
        )

        self._add_section(
            doc,
            "7. Regulatory Information",
            "This notification is provided in accordance with Section 8(6) of the Digital "
            "Personal Data Protection Act, 2023 read with the DPDP Rules, 2025. For more "
            "information about data protection rights, contact the Data Protection Board "
            "of India."
        )

        return self._save_document(doc, "Breach_Notification", org_name)

    def generate_ropa(
        self,
        org_name: str,
        processing_activities: List[Dict[str, str]],
    ) -> str:
        """
        Generate Records of Processing Activities (RoPA).

        Note: The DPDPA does not mandate a RoPA (there is no equivalent of GDPR
        Article 30). This document is generated as recommended good practice that
        supports the general obligations of Data Fiduciaries under Section 8, DPDPA
        and audit-readiness (including for Significant Data Fiduciaries under
        Section 10, DPDPA).

        Args:
            org_name: Organization name
            processing_activities: List of dicts with processing activity details

        Returns:
            Path to generated document
        """
        processing_activities = processing_activities or []

        def _fmt(value, fallback):
            """Format a cell value, joining lists and falling back to a fill-in marker."""
            if value is None or value == "" or value == []:
                return fallback
            if isinstance(value, (list, tuple)):
                return ", ".join(str(v) for v in value)
            return str(value)

        doc = self._create_document("Records of Processing Activities (RoPA)", org_name)

        # Introduction
        self._add_section(
            doc,
            "1. Introduction",
            f"This document contains the {org_name} Records of Processing Activities (RoPA), "
            "maintained as recommended good practice. It documents personal data processing "
            "activities within the organization to support compliance with the obligations of "
            "Data Fiduciaries under Section 8, DPDPA and audit-readiness."
        )

        # Purpose and Status
        self._add_section(
            doc,
            "2. Purpose and Legal Status (Good Practice)",
            "The Digital Personal Data Protection Act, 2023 does not itself require a RoPA "
            "(there is no equivalent of GDPR Article 30). Maintaining these records is a "
            "recommended good practice that helps demonstrate compliance with the general "
            "obligations of a Data Fiduciary under Section 8, DPDPA, and supports periodic "
            "Data Protection Impact Assessments and audits applicable to Significant Data "
            "Fiduciaries under Section 10, DPDPA. Records include: purposes, categories of "
            "Data Principals, data categories, recipients, retention periods, and security "
            "safeguards."
        )

        # Processing Activities Table
        self._add_section(doc, "3. Processing Activities")

        # Create comprehensive table
        table = doc.add_table(rows=len(processing_activities) + 1, cols=9)
        table.style = 'Light Grid Accent 1'

        # Header row
        headers = [
            "Activity",
            "Purpose",
            "Legal Basis",
            "Data Categories",
            "Data Principals",
            "Recipients",
            "Retention",
            "Security Measures",
            "Cross-border",
        ]
        hdr_cells = table.rows[0].cells
        for idx, header in enumerate(headers):
            hdr_cells[idx].text = header

        # Data rows
        for row_idx, activity in enumerate(processing_activities, 1):
            cells = table.rows[row_idx].cells
            cells[0].text = _fmt(
                activity.get("activity") or activity.get("name"),
                "[TO BE COMPLETED: activity name]",
            )
            cells[1].text = _fmt(activity.get("purpose"), "[TO BE COMPLETED: purpose]")
            cells[2].text = _fmt(
                activity.get("legal_basis"),
                "[TO BE COMPLETED: Consent (Section 6) / legitimate use (Section 7)]",
            )
            cells[3].text = _fmt(
                activity.get("data_categories"), "[TO BE COMPLETED: data categories]"
            )
            cells[4].text = _fmt(
                activity.get("data_principals"), "[TO BE COMPLETED: Data Principals]"
            )
            cells[5].text = _fmt(
                activity.get("recipients"), "[TO BE COMPLETED: recipients]"
            )
            cells[6].text = _fmt(
                activity.get("retention"), "[TO BE COMPLETED: retention period]"
            )
            cells[7].text = _fmt(
                activity.get("security_measures"),
                "[TO BE COMPLETED: security safeguards]",
            )
            cells[8].text = _fmt(
                activity.get("cross_border"), "[TO BE COMPLETED: Yes/No]"
            )

        # Data Principal Rights
        self._add_section(doc, "4. Data Principal Rights (Sections 11-14, DPDPA)")
        doc.add_paragraph(
            "For each processing activity, Data Principals have the following rights:"
        )
        rights = [
            "Right to Access Information (Section 11): Obtain a summary of processed data and "
            "processing activities",
            "Right to Correction, Completion and Updating (Section 12): Correct inaccurate data",
            "Right to Erasure (Section 12 read with Section 8(7)): Request erasure under "
            "specified conditions",
            "Right to Withdraw Consent (Section 6(4)): Withdraw consent for processing",
            "Right to Grievance Redressal (Section 13): File complaints for violations",
            "Right to Nominate (Section 14): Nominate someone to exercise rights in the event "
            "of death or incapacity",
        ]
        for right in rights:
            doc.add_paragraph(right, style='List Bullet')

        # Review and Updates
        self._add_section(doc, "5. Review and Updates")
        doc.add_paragraph(
            "This RoPA is reviewed and updated [TO BE COMPLETED: review frequency, e.g. "
            "annually] or whenever processing activities change.\n"
            "Last reviewed: [TO BE COMPLETED: date]\n"
            "Next review: [TO BE COMPLETED: date]"
        )

        # Approval
        doc.add_paragraph()
        approval_para = doc.add_paragraph(
            f"Approved by: ________________ Date: ________________"
        )
        approval_para.paragraph_format.space_before = Pt(12)

        return self._save_document(doc, "Records_of_Processing_Activities", org_name)

    def generate_grievance_policy(
        self,
        org_name: str,
        dpo_name: str = None,
        contact_email: str = None,
        grievance_contact: str = None,
        resolution_timeframe: str = None,
    ) -> str:
        """
        Generate a Grievance Redressal Policy per Section 13 read with
        Section 8(10), DPDPA.

        Args:
            org_name: Organization name
            dpo_name: Data Protection Officer name
            contact_email: Contact email for grievances
            grievance_contact: Alias for contact_email (app.py compatibility)
            resolution_timeframe: Target timeframe for resolving grievances

        Returns:
            Path to generated document
        """
        contact_email = contact_email or grievance_contact or "[TO BE COMPLETED: grievance contact email]"
        dpo_name = dpo_name or "[TO BE COMPLETED: DPO / contact person name]"
        resolution_timeframe = resolution_timeframe or "90 days"

        doc = self._create_document("Grievance Redressal Policy", org_name)

        # Preamble
        self._add_section(
            doc,
            "1. Introduction",
            f"{org_name} is committed to addressing the grievances of Data Principals regarding "
            "violations of their rights under the Digital Personal Data Protection Act, 2023 (DPDPA). "
            "This policy outlines the grievance mechanism and timelines for resolution."
        )

        # Legal Framework
        self._add_section(
            doc,
            "2. Legal Framework (Section 13 read with Section 8(10), DPDPA)",
            "Every Data Fiduciary shall establish an effective mechanism to redress the "
            "grievances of Data Principals (Section 8(10), DPDPA). Data Principals have the "
            "right to readily available means of grievance redressal (Section 13, DPDPA) and "
            "must exhaust this mechanism before approaching the Data Protection Board of India."
        )

        # What Constitutes a Grievance
        self._add_section(doc, "3. What Constitutes a Grievance")
        grievances = [
            "Unauthorized processing of personal data",
            "Denial of the right to access information about personal data (Section 11)",
            "Failure to correct, complete, or update personal data (Section 12)",
            "Failure to erase personal data upon request (Section 12 read with Section 8(7))",
            "Unauthorized transfer of personal data",
            "Failure to respond to grievance within specified timelines",
            "Any other violation of DPDPA or organizational policies",
        ]
        for grievance in grievances:
            doc.add_paragraph(grievance, style='List Bullet')

        # Filing a Grievance
        self._add_section(doc, "4. How to File a Grievance")

        self._add_subsection(doc, "4.1 Channels for Filing")
        channels = [
            f"Email: {contact_email}",
            "Physical Mail: [TO BE COMPLETED: office address]",
            "Online Form: [TO BE COMPLETED: website URL]",
            "In Person: [TO BE COMPLETED: office location]",
        ]
        for channel in channels:
            doc.add_paragraph(channel, style='List Bullet')

        self._add_subsection(doc, "4.2 Information Required")
        doc.add_paragraph("When filing a grievance, please provide:")
        info_required = [
            "Your full name and contact information",
            "Description of the grievance with dates",
            "Relevant personal data or documentation",
            "Action you expect to address the grievance",
            "Any previous communication regarding the grievance",
        ]
        for info in info_required:
            doc.add_paragraph(info, style='List Bullet')

        # Processing Timeline
        self._add_section(doc, "5. Grievance Processing Timeline")

        self._add_subsection(
            doc,
            "5.1 Acknowledgment (Within 48 hours)",
            f"We acknowledge receipt of your grievance within 48 hours. Acknowledgment will include "
            "a reference number, expected resolution timeline, and DPO contact information."
        )

        self._add_subsection(
            doc,
            f"5.2 Investigation (Within {resolution_timeframe})",
            "We investigate the grievance and take necessary corrective actions. You will be updated "
            "on the progress of investigation."
        )

        self._add_subsection(
            doc,
            f"5.3 Resolution (Within {resolution_timeframe})",
            "We provide a detailed response addressing your grievance and actions taken. If the "
            "grievance is rejected, we provide reasons for rejection."
        )

        # Escalation
        self._add_section(doc, "6. Escalation to the Data Protection Board of India")
        doc.add_paragraph(
            "If you are not satisfied with our response, you may escalate your grievance to the "
            "Data Protection Board of India after exhausting this grievance mechanism. "
            "Contact details:\n"
            "[TO BE COMPLETED: Data Protection Board of India address]\n"
            "[TO BE COMPLETED: phone number]\n"
            "[TO BE COMPLETED: website URL]"
        )

        # No Retaliation
        self._add_section(doc, "7. No Retaliation Policy")
        doc.add_paragraph(
            "We do not retaliate against any Data Principal for filing a grievance in good faith. "
            "Retaliation or harassment will be treated as a serious violation."
        )

        # Data Protection Officer
        self._add_section(doc, "8. Data Protection Officer / Contact Person (Section 8(9), DPDPA)")
        dpo_info = [
            f"Name: {dpo_name}",
            f"Email: {contact_email}",
            "Phone: [TO BE COMPLETED: contact number]",
            "Office Hours: [TO BE COMPLETED: office hours]",
        ]
        for info in dpo_info:
            doc.add_paragraph(info, style='List Bullet')

        # Contact Information
        self._add_section(doc, "9. Contact Information")
        contact_details = [
            f"Organization: {org_name}",
            f"Email: {contact_email}",
            "Address: [TO BE COMPLETED: office address]",
            "Phone: [TO BE COMPLETED: contact number]",
            "Website: [TO BE COMPLETED: website URL]",
        ]
        for detail in contact_details:
            doc.add_paragraph(detail, style='List Bullet')

        # Policy Review
        self._add_section(doc, "10. Policy Review")
        doc.add_paragraph(
            "This policy is reviewed annually and updated to reflect changes in regulations, "
            "organizational practices, and feedback from Data Principals."
        )

        return self._save_document(doc, "Grievance_Redressal_Policy", org_name)

    def generate_all_documents(self, org_name: str, org_details: Dict) -> Dict[str, str]:
        """
        Generate all DPDPA compliance documents at once.

        Args:
            org_name: Organization name
            org_details: Dictionary containing all details for document generation

        Returns:
            Dictionary with document names and their file paths
        """
        documents = {}

        # Privacy Policy
        documents["Privacy Policy"] = self.generate_privacy_policy(
            org_name=org_name,
            industry=org_details.get("industry", "[TO BE COMPLETED: industry]"),
            data_categories=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information", "Usage Data"]
            ),
            purposes=org_details.get(
                "purposes",
                ["Service Delivery", "Customer Communication", "Improvement"]
            ),
            retention_period=org_details.get("retention_period", "3 years"),
            contact_email=org_details.get("contact_email", "[TO BE COMPLETED: contact email]"),
            dpo_name=org_details.get("dpo_name", "[TO BE COMPLETED: DPO name]"),
        )

        # Consent Notice
        documents["Consent Notice"] = self.generate_consent_notice(
            org_name=org_name,
            purpose=org_details.get("purpose", "[TO BE COMPLETED: processing purpose]"),
            data_categories=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information"]
            ),
            processors=org_details.get("processors", ["[TO BE COMPLETED: processor name]"]),
            retention=org_details.get("retention_period", "3 years"),
        )

        # Data Processing Agreement
        documents["Data Processing Agreement"] = self.generate_dpa(
            controller_name=org_name,
            processor_name=org_details.get("processor_name", "[TO BE COMPLETED: processor name]"),
            processing_purposes=org_details.get(
                "purposes",
                ["Service Delivery", "Data Analysis"]
            ),
            data_types=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information"]
            ),
        )

        # DPIA Report
        documents["DPIA Report"] = self.generate_dpia(
            org_name=org_name,
            project_name=org_details.get("project_name", "[TO BE COMPLETED: project name]"),
            processing_description=org_details.get(
                "processing_description",
                "[TO BE COMPLETED: description of processing activities]"
            ),
            data_types=org_details.get(
                "data_categories",
                ["Personal Identifiers", "Contact Information"]
            ),
            risk_assessment=org_details.get(
                "risk_assessment",
                {
                    "Unauthorized Access": "Implement encryption and access controls",
                    "Data Loss": "Implement backups and disaster recovery",
                }
            ),
        )

        # Breach Notification
        documents["Breach Notification"] = self.generate_breach_notification(
            org_name=org_name,
            breach_date=org_details.get("breach_date", "[TO BE COMPLETED: breach date]"),
            discovery_date=org_details.get("discovery_date", "[TO BE COMPLETED: discovery date]"),
            description=org_details.get(
                "breach_description",
                "[TO BE COMPLETED: description of breach]"
            ),
            data_affected=org_details.get(
                "data_affected",
                ["Personal Identifiers", "Contact Information"]
            ),
            individuals_count=org_details.get("individuals_count", 0),
            measures_taken=org_details.get(
                "measures_taken",
                ["Secured systems", "Notified affected parties"]
            ),
        )

        # Records of Processing Activities
        documents["RoPA"] = self.generate_ropa(
            org_name=org_name,
            processing_activities=org_details.get(
                "processing_activities",
                [
                    {
                        "activity": "Customer Data Processing",
                        "purpose": "Service Delivery",
                        "legal_basis": "Consent (Section 6, DPDPA)",
                        "data_categories": "Personal Identifiers, Contact Info",
                        "data_principals": "Customers",
                        "recipients": "Internal Teams",
                        "retention": "3 years",
                        "security_measures": "Encryption, Access Control",
                        "cross_border": "No",
                    }
                ],
            ),
        )

        # Grievance Redressal Policy
        documents["Grievance Redressal Policy"] = self.generate_grievance_policy(
            org_name=org_name,
            dpo_name=org_details.get("dpo_name", "[TO BE COMPLETED: DPO name]"),
            contact_email=org_details.get("contact_email", "[TO BE COMPLETED: contact email]"),
        )

        return documents


def main():
    """Test the DocumentGenerator module."""
    print("Testing DocumentGenerator Module...")
    print("=" * 50)

    # Initialize generator (uses a unique per-instance temporary directory)
    generator = DocumentGenerator()
    print(f"Output directory: {generator.output_dir}")

    # Test organization details
    org_details = {
        "industry": "Technology",
        "data_categories": [
            "Name",
            "Email Address",
            "Phone Number",
            "Usage Data",
            "IP Address"
        ],
        "purposes": [
            "Service Delivery",
            "Customer Communication",
            "Service Improvement",
            "Compliance with Legal Obligations"
        ],
        "retention_period": "3 years or until consent withdrawn",
        "contact_email": "privacy@svikruti.ai",
        "dpo_name": "Data Protection Officer",
        "purpose": "Providing AI-powered DPDPA compliance services",
        "processor_name": "Cloud Infrastructure Provider",
        "project_name": "DPDPA Compliance Portal",
        "processing_description": "Processing personal data for compliance services",
        "risk_assessment": {
            "Unauthorized Access": "Implement encryption and access controls",
            "Data Loss": "Daily backups and disaster recovery",
            "Unlawful Processing": "Regular audits and privacy impact assessments"
        },
        "processors": ["Cloud Provider A", "Service Provider B"],
        "processing_activities": [
            {
                "activity": "User Registration",
                "purpose": "Account Creation",
                "legal_basis": "Consent (Section 6, DPDPA)",
                "data_categories": "Name, Email, Password",
                "data_principals": "Website Visitors",
                "recipients": "Internal IT Team",
                "retention": "Until account deletion",
                "security_measures": "Encryption, Hashing",
                "cross_border": "No"
            },
            {
                "activity": "Service Usage Analytics",
                "purpose": "Service Improvement",
                "legal_basis": "Consent (Section 6, DPDPA)",
                "data_categories": "Usage Data, IP Address",
                "data_principals": "Registered Users",
                "recipients": "Analytics Team",
                "retention": "2 years",
                "security_measures": "Anonymization, Access Control",
                "cross_border": "No"
            }
        ]
    }

    # Generate individual documents
    print("\nGenerating individual documents...")
    print("-" * 50)

    privacy_policy = generator.generate_privacy_policy(
        org_name="Svikruti.ai",
        industry=org_details["industry"],
        data_categories=org_details["data_categories"],
        purposes=org_details["purposes"],
        retention_period=org_details["retention_period"],
        contact_email=org_details["contact_email"],
        dpo_name=org_details["dpo_name"]
    )
    print(f"✓ Privacy Policy: {privacy_policy}")

    consent_notice = generator.generate_consent_notice(
        org_name="Svikruti.ai",
        purpose=org_details["purpose"],
        data_categories=org_details["data_categories"],
        processors=org_details["processors"],
        retention=org_details["retention_period"]
    )
    print(f"✓ Consent Notice: {consent_notice}")

    dpa = generator.generate_dpa(
        controller_name="Svikruti.ai",
        processor_name=org_details["processor_name"],
        processing_purposes=org_details["purposes"],
        data_types=org_details["data_categories"]
    )
    print(f"✓ DPA: {dpa}")

    dpia = generator.generate_dpia(
        org_name="Svikruti.ai",
        project_name=org_details["project_name"],
        processing_description=org_details["processing_description"],
        data_types=org_details["data_categories"],
        risk_assessment=org_details["risk_assessment"]
    )
    print(f"✓ DPIA Report: {dpia}")

    breach = generator.generate_breach_notification(
        org_name="Svikruti.ai",
        breach_date="01-03-2026",
        discovery_date="02-03-2026",
        description="Unauthorized access to customer database",
        data_affected=org_details["data_categories"],
        individuals_count=1000,
        measures_taken=["Secured systems", "Notified affected parties", "Enhanced monitoring"]
    )
    print(f"✓ Breach Notification: {breach}")

    ropa = generator.generate_ropa(
        org_name="Svikruti.ai",
        processing_activities=org_details["processing_activities"]
    )
    print(f"✓ RoPA: {ropa}")

    grievance = generator.generate_grievance_policy(
        org_name="Svikruti.ai",
        dpo_name=org_details["dpo_name"],
        contact_email=org_details["contact_email"]
    )
    print(f"✓ Grievance Policy: {grievance}")

    # Generate all documents at once
    print("\n" + "=" * 50)
    print("Generating all documents...")
    print("-" * 50)

    all_docs = generator.generate_all_documents(
        org_name="Svikruti.ai",
        org_details=org_details
    )

    for doc_name, doc_path in all_docs.items():
        print(f"✓ {doc_name}: {doc_path}")

    print("\n" + "=" * 50)
    print(f"All documents generated successfully in: {generator.output_dir}")
    print("=" * 50)


if __name__ == "__main__":
    main()
